apiVersion: v1
kind: Namespace
metadata:
  annotations:
    note: Este es el ambiente de Producion
  labels:
    app: public-api
    team: devops
  name: public
---
apiVersion: v1
data:
  PRIVATE_API: PROD_ENDPOINT
kind: ConfigMap
metadata:
  annotations:
    note: Este es el ambiente de Producion
  labels:
    app: public-api
    team: devops
  name: cm-private-api
  namespace: public
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImIzZGxiakUzTVRBNlpHTnJjbDl3WVhSZmJEVmFibWRsVTB0WWRsWTJXSGxCTkc1QlNFTmpjMmhsY2paQiIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS9hY2Nlc3MtdG9rZW4iOiB7CgkJCSJhdXRoIjogImIzZGxiakUzTVRBNlpYbEthR0pIWTJsUGFVcFRWWHBKTVU1cFNYTkpibEkxWTBOSk5rbHJjRmhXUTBselNXMTBjRnBEU1RaSmJtaFpZVE5DUTJSRVRubFdNMDE1VW5reE1WbHFiSE5qUlhCdVkxTktPUzVsZVVwdlpFaFNkMk42YjNaTU1tZ3hXV2sxYTJJeVRuSmFXRWwxV1RJNWRFbHFjRGRKYlZaMFdWZHNjMGxxYjJsaU1qRnFXVEpHYzJKSFJtbE5WR1JCV2pJeGFHRlhkM1ZaTWpsMFNXbDNhV015Vm5wak1teDJZbXc1Y0ZwRFNUWkphbU4zVGtSSmVscHRWbWxNVjBwcVRucFpkRTVIV1hkWlV6Rm9XVzFXYkV4VVdtdE9WRkUxV21wc2FGcEhXVFJPUTBselNXNU9kbVJZU21wYVUwazJTVzFrZG1JeVpITmFVekYyV1ZoV01HRkVTV2xNUTBveFl6SldlV0p0Um5SYVUwazJTVzA1TTFwWE5IaE9la1YzU1dsM2FXUllWbkJhUTBrMlNXMWFiVmxVVlhsYVIwVTFURmRaZUU1cVdYUk9SRlV5VGxNeGFWbDZUVFZNVkVreFRrUk9hMDFVU214YVZFRjNUVU5LT1V4RFNuQmpNMDFwVDJsS2IyUklVbmRqZW05MlRESjRkbG95YkhWTWJWSjJXVEowYkdOcE5XcGlNakIyU1dsM2FXTXpWbWxKYW05cFdqSTVkbG95ZUd4TVZ6bG9aRmhTYjAxdWQzaE5WRkYzVDBSRk5VMUVZM2hQVkUxNVRsUkpkMDlVYXpSTlZGbHBURU5LYUdSWFVXbFBiSE5wWVVoU01HTklUVFpNZVRsdlpGZEpkVnBIT1dwaE1sWjVURzFPZG1KVFNYTkpiV2d3WkVoQ2VrOXBPSFphUnpscVlUSldlVXhZUW5saU1sRjFaRmhOZFZsWVZqQmhSRUYxV1RJNWRFd3pWbnBhV0Vwd1ltMWFka2xzTUhOSmJXeG9aRU5KTmsxVVl6Uk9WR00wVFZSak0wOURkMmxhV0doM1NXcHZlRTU2WnpGT2VtZDVUbXBqTkV4RFNucFpNamwzV2xOSk5rbHRPWGRhVnpWd1drTkNkbHB0V25OaFZ6VnNXREpHYWxreVZucGplVWx6U1cxR05tTkRTVFpKYTNjd1pHcENhMkpYZUU5UmJrSmFWbGR3U0ZJeVJtbE5SVTE1VTI1U2JsWkhaRmxqYWtaU1pXcFNhMGx1TUM1NFpGbDFTRFpQWDNsSlF6bHNlRGxGVlVSa1FsZHZiMmg1ZG1WdWEyd3pOMjh6YlY4NVNUWnhibU5YZWxKTlNXZDRjVlZhUWpOMVNUSkRORTFEWlROT1RGWnFhbXR6T0VFemJUUnJRbUpsWDJwa1RYaFBNelkyUlhCQ1MzVkNTbGRWU0U1MlZVWlZXall6ZGxwZk4zWmxMVzF5Wkhkc1ZGZEhlVTQ0VFhodlZFWTVkMFZTT0c5aGVrc3pZVU5CWDJKWFRsRjVUelU1WWtOVmMxWkJXWFJNUVdSak5IcFJZakpEUm5wWmNXdFhkMUJKUVZGemEyZDJVMlJGVkY5NE5VVXRURmt0Vld4UWRFVlZZMmsyYTJkRVNqSlNZV3Q2TUdsRU5WVlRiSGN5T0RFeWJHOW9PSGRMUVhCaloyUlBRM0F6TmxKNWRGZHlOVmN0UWxaWVNuUnJSWEJDUWtob1dtYzFXamR5VG5wUVNXNXJUMFJ5V1VSSmVWVmhabk10VDFOQ1YxTnFjVTVtY1V0MVVuZGxYM0p4WVRBNFV5MXhNbTlmT0dWeVdWVlhXbE5qYjJwclMyRmtjMHN4UlZjNVNtZzFlRFpwUjBFPSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS9yZWZyZXNoLXRva2VuIjogewoJCQkiYXV0aCI6ICJiM2RsYmpFM01UQTZkakV1VFZGU1QwNU5hMVl5U2pWTU1rcHBSVGxUU0Y5SVprdE5UVUYxYVhRM2RHMW1TM2x4Ym1KcVpuRmhNREl5ZG1GNU5sTTNNbGxCZG5OalJHMXBXRmhxTW1GaFRqWjZRVFJpZVRsUmNXRm9kVkJJWDI5a2NHUTRMaTVNTkhZd1pHMXNUa0p3V1ZWcVIwZGhZakJETWtwMFoxUm5XSEl4VVhvMFpBPT0iCgkJfQoJfQp9
kind: Secret
metadata:
  annotations:
    note: Este es el ambiente de Producion
  labels:
    app: public-api
    team: devops
  name: regcred
  namespace: public
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Este es el ambiente de Producion
  labels:
    app: public-api
    team: devops
  name: public-api
  namespace: public
spec:
  ports:
  - name: public-api
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: public-api
    team: devops
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Este es el ambiente de Producion
  labels:
    app: public-api
    team: devops
  name: public-api
  namespace: public
spec:
  selector:
    matchLabels:
      app: public-api
      team: devops
  template:
    metadata:
      annotations:
        note: Este es el ambiente de Producion
      labels:
        app: public-api
        team: devops
      name: public-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm-private-api
        image: owen1710/kubelabs_publicapi:1.0.0
        imagePullPolicy: Always
        name: public-api
        ports:
        - containerPort: 3000
          name: public-api
        resources:
          limits:
            cpu: 20m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 50Mi
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    note: Este es el ambiente de Producion
  labels:
    app: public-api
    team: devops
  name: public-api
  namespace: public
spec:
  rules:
  - host: api.owen.kubelabs.dev
    http:
      paths:
      - backend:
          service:
            name: public-api
            port:
              number: 3000
        path: /
        pathType: Prefix
      - backend:
          service:
            name: public-api
            port:
              number: 3000
        path: /graphql
        pathType: Prefix
