apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels:
  app: public-api
  team: devops

commonAnnotations:
  note: "Este es el ambiente de STAGE"

resources:
  - ns.yaml
  - ../../base


patches:
  - target:
      kind: ConfigMap
      name: cm-private-api
    path: cm-patch.yaml
  - target:
      kind: Ingress
      name: public-api
    path: ing-patch.yaml
  - target:
      kind: Deployment
      name: public-api
    path: deploy.yaml

# Image patch
images:
  - name: KUSTOMIZE-DEFINED
    newName: owen1710/kubelabs_publicapi
    newTag: 1.0.0  # <- cambiar la version correcta.
